"""create workspace table

Revision ID: 77da9e7b4f7e
Revises: 7f9ccb8d6f74
Create Date: 2026-08-06 23:11:42.557210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77da9e7b4f7e'
down_revision: Union[str, Sequence[str], None] = '7f9ccb8d6f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('workspace_membership_user_id_fkey'), 'workspace_membership', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_membership', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_membership', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_membership_user_id_fkey'), 'workspace_membership', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
