from enum import Enum
class EventType(str,Enum):
    SEND_VERIFICATION_EMAIL="SEND_VERIFICATION_EMAIL"
    PASSWORD_RESET = "PASSWORD_RESET"

    WORKSPACE_CREATED = "WORKSPACE_CREATED"

    USER_REGISTERED = "USER_REGISTERED"
    SEND_WORKSPACE_INVITATION = "SEND_WORKSPACE_INVITATION"
    NOTE_UPLOADED = "NOTE_UPLOADED"
class Status(str,Enum):
    PENDING="PENDING"
    PUBLISHED="PUBLISHED"
    COMPLETED="COMPLETED"  
    FAILED="FAILED"  
